# Generated by Django 3.2.12 on 2022-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('diver', 'Diver'), ('dress', 'Dress'), ('sport', 'Sport'), ('pilot', 'Pilot'), ('mechanical', 'Mechanical'), ('quartz', 'Quartz')], max_length=15)),
                ('brand', models.CharField(max_length=40)),
                ('production_year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='watches')),
                ('for_sale_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watches.watch')),
            ],
        ),
    ]
